CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'FOR_SALE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_posts_seller
                   FOREIGN KEY (seller_id) REFERENCES users (id),

    CONSTRAINT ck_posts_price
                   CHECK (price >= 0),

    CONSTRAINT ck_posts_status
                   CHECK (status IN ('FOR_SALE', 'RESERVED', 'COMPLETED'))
);

CREATE INDEX idx_posts_seller_id ON posts (seller_id);