CREATE TABLE social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_social_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT uk_social_accounts_provider_subject
        UNIQUE (provider, provider_subject),

    CONSTRAINT uk_social_accounts_user_provider
        UNIQUE (user_id, provider),

    CONSTRAINT ck_social_accounts_provider
        CHECK (provider IN ('GOOGLE')),

    CONSTRAINT ck_social_accounts_subject_not_blank
        CHECK (length(trim(provider_subject)) > 0)
);
